tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'bat'
brew 'curl'
brew 'fzf'
brew 'ripgrep'
brew 'ruby-build'
brew 'tmux'
brew 'vim'
brew 'zsh'
brew 'reattach-to-user-namespace'
