# /Users/nickborromeo/.config/tmuxinator/dotcom.yml

name: dotcom
# for local
# root: ~/github/github

# for codespaces
root: /workspaces/github

windows:
  - terminal:
  - vim: vim .
  - console:
    - bin/console
  - server:
    - script/server
  - gh cli:

